#!/bin/bash
##Potaje6
#Simple script to organise 3D files and stuff
#Redone from zero cuz how i did before was totally retarded, i still dunno why tf i did it like that
#Made because im too lazy to decompress and keep it organized over 2 days

STUFF=/home/dmolinao/3D
PROJECTS=${STUFF}/PROJECTS
PACKAGES=${STUFF}/PACKAGES
ZIP_FILE=$1
NEW_PROJECT=$(basename $1 | sed 's/.zip//')

if [ -z $ZIP_FILE ]; then
	echo "Give a file to work with mah nigga"
fi

unzip -d ${PROJECTS}/${NEW_PROJECT} ${ZIP_FILE}
if [ $? -ne 0 ]; then
	echo "Something went wrong with $ZIP_FILE, check it"
	exit 1
fi
mkdir ${PROJECTS}/${NEW_PROJECT}/GCODE
mv ${ZIP_FILE} ${PACKAGES}


