#!/bin/ksh
##Daniel Molina
##Script para hacer recordatorios por consola

export DISPLAY=:0
BASEDIR=$(dirname "$0")
AGENDA=$BASEDIR/parametros/agenda
#FECHA=$(date +%Y-%m-%d/%H:%M)
FECHA=$(date +%Y%m%d%H%M)
i=0
z=0
LISTA_TAREAS=$(grep -v ^# $AGENDA |sed -e 's/[-\/:]//g')
PF=-gt
DAYS=0
HOURS=0
MINS=0
NEW_MODE=0
NUMERIC='^[0-9]+$'


print_uso(){
cat <<EOF
Script para hacer recordatorios por todas las consolas para evitar olvidos causados por mi alzheimer
Usa el fichero en parametros/agenda donde se ejecuta para crear recordatorios
Usa -a para meterlo al final del fichero
Con el formato de "2016-08-05/08:38 RECORDATORIO"
Uso: ./agenda [--now] [-l/--list] [-e/--edit] [--help] [-a/--add] [-f/--future]


--now muestra la fecha de ahora con el formato para la lista
-l/--list lista todas las tareas del fichero que no se hayan realizado/comentado
-e/--edit edita el fichero de la agenda
-a/--add
-f/--future ver las tareas planificadas en el futuro
--help muestra esta ayuda
Modo para añadir entrada nueva para vaguermonguers:
-d/--days +x dias a añadir la entrada de la hora actual
-h/--hours +x horas a añadir la entrada de la hora actual
-m/--minutes +x minutos a añadir la entrada de la hora actual
-n/--new [mensaje] mensaje para la notificacion, OJO, pon esta mierda al final, no le busques las cosquillas al script


EOF
}


while [ $# -gt 0 ];
do
        case $1 in
        "--now") date +%Y-%m-%d/%H:%M
        exit
;;
        "-l"|"--list") grep -v ^# $AGENDA 
        exit
;;
        "--help") print_uso
        exit
;;
        "-n"|"--new") NEW_MODE=1
                    shift
                    if [ -z $@ ]; then
                    echo "No argument given"
                    exit
                    fi 
                    expr $DAYS + $HOURS + $MINS | grep -q 0
                    echo $(date -d "+$DAYS days $HOURS hours $MINS minutes" +%Y-%m-%d/%H:%M) "$@" >> $AGENDA
        exit
;;
        "-d"|"--days") DAYS=$2
            if [ "$DAYS" -eq "$DAYS" ]; then
                echo
                else
                echo "NO TIME GIVEN!!"
                exit
            fi 2>/dev/null
        shift
        shift
;;
        "-h"|"--hours") HOURS=$2
            if [ "$HOURS" -eq "$HOURS" ]; then
                echo
                else
                echo "NO TIME GIVEN!!"
                exit
            fi 2>/dev/null
        shift
        shift
;;
        "-m"|"--minutes") MINS=$2
            if [ "$MINS" -eq "$MINS" ]; then
                echo
                else
                echo "NO TIME GIVEN!!"
                exit
            fi 2>/dev/null
        shift
        shift
;;
        "-e"|"--edit") vi $AGENDA
        exit
;;
        "-a"|"--add") shift
                    if [ -z $@ ]; then
                    echo "No argument given"
                    exit
                    fi 
        			echo "$@" >> $AGENDA
        exit
;;
        "-f"|"--future") echo "Cambios planificados:"  
						PF=-lt
		shift
						
;;
        *) 
        shift
esac
done



grep -v ^# $AGENDA | grep -v ^$ |sed -e 's/[-\/:]//g' | while read PLANIFICADO[$i] TAREA[$i]; do
i=$(($i+1))
done


until [ $z -eq $i ] ; do
	if [ $FECHA $PF "${PLANIFICADO[$z]}" ] ; then
#		echo ${TAREA[$z]} "planificado para " ${PLANIFICADO[$z]} | wall -n
		beep
                notify-send "${TAREA[$z]} planificado para  ${PLANIFICADO[$z]}"
                 zenity --title "POTAGENDA" --info --text "${TAREA[$z]} planificado para  ${PLANIFICADO[$z]}" 2>&1 /dev/null
	fi
	#echo ${PLANIFICADO[$z]} ${TAREA[$z]}
	z=$(($z+1))
done

