#!/bin/ksh
###Daniel Molina
##Script para hacer recordatorios por notificacion flotante y con ventana

export DISPLAY=:0
EXEC_DIR=$(dirname "$0")
AGENDA=$EXEC_DIR/parametros/agenda
#FECHA=$(date +%Y-%m-%d/%H:%M)
FECHA=$(date +%Y%m%d%H%M)
i=0
z=0
LISTA_TAREAS=$(grep -v ^# $AGENDA |sed -e 's/[-\/:]//g')
PF=-ge
DAYS=0
HOURS=0
MINS=0
NEW_MODE=0
NUMERIC='^[0-9]+$'
ICO=$EXEC_DIR/parametros/pepesuicide.jpg
SOUND=/home/dmolinao/alla/infidel/nr10.mp3.wav


print_uso(){
cat <<EOF
Script para hacer recordatorios por notificacion flotante y con ventana
Usa el fichero en parametros/agenda donde se ejecuta para crear recordatorios
Usa -a para meterlo al final del fichero
Con el formato de "2016-08-05/08:38 RECORDATORIO"
Uso: ./agenda [--now] [-l/--list] [-e/--edit] [--help] [-a/--add] [-f/--future]


--now muestra la fecha de ahora con el formato para la lista
-l/--list lista todas las tareas del fichero que no se hayan realizado/comentado
-e/--edit edita el fichero de la agenda
-a/--add
-f/--future ver las tareas planificadas en el futuro (sobre todo para debuggear, para ver tareas pendientes utiliza -l)
--help muestra esta ayuda
Modo para añadir entrada nueva para vaguermonguers:
-d/--days +x dias a añadir la entrada de la hora actual
-h/--hours +x horas a añadir la entrada de la hora actual
-m/--minutes +x minutos a añadir la entrada de la hora actual
-n/--new [mensaje] mensaje para la notificacion, OJO, pon esta mierda antes de la notificacion, si no se pone no añadira la entrada, no le busques las cosquillas al script, esta hecho para gente con cabeza


EOF
}


while [ $# -gt 0 ];
do
        case $1 in
        "--now") date +%Y-%m-%d/%H:%M
        exit
;;
        "-l"|"--list") grep -v ^# $AGENDA 
        exit
;;
        "--help") print_uso
        exit
;;
        "-n"|"--new") NEW_MODE=1
                    shift
                    if [ -z $@ ]; then
                    echo "No argument given"
                    exit
                    fi 
                    expr $DAYS + $HOURS + $MINS | grep -q 0
                    echo $(date -d "+$DAYS days $HOURS hours $MINS minutes" +%Y-%m-%d/%H:%M) "$@" | tee -a $AGENDA

        exit
;;

        "-d"|"--days") DAYS=$2
        if ! [[ "$DAYS" =~ $NUMERIC ]]; then
            echo "NO TIME GIVEN!!"
            exit 1
        fi
        shift
        shift
;;
        "-h"|"--hours") HOURS=$2
        if ! [[ "$HOURS" =~ $NUMERIC ]]; then
            echo "NO TIME GIVEN!!"
            exit 1
        fi
        shift
        shift
;;
        "-m"|"--minutes") MINS=$2
        if ! [[ "$MINS" =~ $NUMERIC ]]; then
            echo "NO TIME GIVEN!!"
            exit 1
        fi
        shift
        shift
;;
        "-e"|"--edit") vi $AGENDA
        exit
;;
        "-a"|"--add") shift
                    if [ -z $@ ]; then
                    echo "No argument given"
                    exit
                    fi 
        			echo "$@" >> $AGENDA
        exit
;;
        "-f"|"--future") echo "Cambios planificados:"  
						PF=-lt
		shift
						
;;
        *) 
        shift
esac
done



grep -v ^# $AGENDA | grep -v ^$ | while read PLANIFICADO_RAW[$i] TAREA[$i]; do
PLANIFICADO[$i]=$(echo ${PLANIFICADO_RAW[$i]} | sed -e 's/[-\/:]//g')
i=$(($i+1))
done


until [ $z -eq $i ] ; do
	if [ $FECHA $PF "${PLANIFICADO[$z]}" ] ; then
#		echo ${TAREA[$z]} "planificado para " ${PLANIFICADO[$z]} | wall -n
		#beep
        aplay $SOUND > /dev/null 2>&1
                notify-send -i $ICO POTAGENDA "${TAREA[$z]} planificado para  ${PLANIFICADO[$z]}" > /dev/null 2>&1
                 #zenity --title "POTAGENDA" --info --text "${TAREA[$z]} planificado para  ${PLANIFICADO[$z]}" 2>&1 /dev/null
                zenity --question --text="${TAREA[$z]} planificado para  ${PLANIFICADO_RAW[$z]}\n\n5 minuticos mas?" --default-cancel  --title "POTAGENDA" > /dev/null 2>&1
                if [ $? -eq 0 ]; then
                #No lo aplazara si el recordatorio contiene "/", paso de corregirlo, no pongas putas barras surnormal
                 sed -i "s/^$(echo ${PLANIFICADO_RAW[$z]} | sed 's/\//\\\//') ${TAREA[$z]}/$(date -d "+5 minutes" +%Y-%m-%d\/%H:%M | sed 's/\//\\\//') ${TAREA[$z]}/" $AGENDA
                 notify-send -i $ICO POTAGENDA "${TAREA[$z]} APLAZADO 5 MINUTOS" > /dev/null 2>&1
                fi

	fi
	#echo ${PLANIFICADO[$z]} ${TAREA[$z]}
	z=$(($z+1))
done

echo "Finished checking $i entries"
