#!/bin/ksh
##Daniel Molina
##Sync host list

HORA=+%Y-%m-%d--%H:%M:%S
LISTA=$HOME/list
TEMPORAL=$HOME/temp
DESTINO=192.168.150.136
ACTIVE=0
LUSER=dmolinao

##Captura de salida
trap force_exit SIGINT


force_exit(){
        echo 
        echo "Exiting..."
        rm -f $HOME/.ACTIVO
        rm -f $TEMPORAL
        exit 3
}



ssh -i $HOME/.ssh/id_rsa ${LUSER}@${DESTINO} ls $HOME/.ACTIVO > /dev/null  2>&1
if [ $? -eq 0 ]; then
        echo "ShitScript is active at $DESTINO"
        exit 1
fi

echo $$ > $HOME/.ACTIVO

test -f $HOME/.ACTIVO > /dev/null  2>&1
ACTIVE=$?

while [ $ACTIVE -eq 0 ]; do

 
ssh -i $HOME/.ssh/id_rsa ${LUSER}@${DESTINO} ls $HOME/list > /dev/null  2>&1



cat $HOME/.ssh/known_hosts | cut -d "," -f1 | cut -d " " -f1 | uniq -u |sort >> $TEMPORAL
ssh -i $HOME/.ssh/id_rsa ${LUSER}@${DESTINO} cat $HOME/.ssh/known_hosts | cut -d "," -f1 | cut -d " " -f1 | uniq -u |sort >> $TEMPORAL
sort -u $TEMPORAL > $LISTA
rm -f $TEMPORAL
echo "#Last update $(date $HORA) done in $(hostname)" >> $LISTA
scp -i  $LISTA 
scp -i $HOME/.ssh/id_rsa $LISTA ${LUSER}@${DESTINO}: > /dev/null

sleep 600

ls .ACTIVO > /dev/null  2>&1
ACTIVE=$?

done

rm -f .ACTIVO

exit
