#!/bin/ksh
##Potaje6
##Grep stuff in .ssh/known_hosts, typing the whole hostname is for niggers and fags
##Disable ssh's know_hosts encryption to use this

i=0
LUSER=sistemas
x=1
z=0
bold=$(tput bold)
normal=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
color=red
HORA=+%Y-%m-%d--%H:%M:%S
EXEC_DIR=$(dirname $0)
EXEC_NAME=$(basename $0)
LOG_DIR=$EXEC_DIR/logs
LOG_FILE=$LOG_DIR/connections
LIST_FILE=$EXEC_DIR/list
MODE=normie

normie(){
if (( $i % 2 )); then
    color=$red
else
    color=$yellow
fi
}

faggot(){
z=$(($z+1))
if [ $z -eq 6 ]; then z=1; fi
color=$(tput setaf ${z})
}

##Captura de salida
trap force_exit SIGINT


force_exit(){
        echo 
        echo "Exiting..."
        exit 3
}

print_uso(){
cat <<EOF
        Usage:
        ./script [-h|-v|-u|-r] trozo_nombre_conocido_de_maquina
        This shit logs all ur activity for the NSA in $LOG_FILE
        -v verbose mode
        -u user
        -r root
        --faggot = do it faggot
EOF
exit
}

if [ $# -eq 0 ];then
print_uso
fi

while [ $# -gt 0 ];
do
    case $1 in
-h)     
print_uso
;;
-u) LUSER=$2
shift
shift
;;
-r) LUSER=root
shift
;;
--faggot) MODE=faggot
shift
;;
-v) DEBUG=-v
shift
;;
*) break
;;
esac
done

#solo 1 de los 2 modos puede estar activo, o fichero list o known_hosts
cat $HOME/.ssh/known_hosts | cut -d "," -f1 | cut -d " " -f1 | uniq -u |sort | grep $1 |\

#if [ ! -f $LIST_FILE ]; then
#    touch $LIST_FILE
#fi

#grep -v ^# $LIST_FILE |\
uniq -u |sort | grep $1 |\
while read MAQUINA ; do
i=$(($i+1))

$MODE

MAQUINA[$i]=$MAQUINA
eval echo "${color}$i${normal} = ${color}$MAQUINA${normal}"
done

case $i in
0) echo "Not found in list"
        nc $DEBUG -w 3 -z $1 22 > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "${bold}$1${normal} exist and got 22 open"
            ssh $DEBUG -l $LUSER $1
        fi
        exit 
;;      
1) echo "${bold}${MAQUINA[$i]}${normal} ${bold}FOUND${normal}"
        ssh $DEBUG -l $LUSER ${MAQUINA[$i]}
;;      
*)

printf "Type 1 to ${bold}$i${normal} to login: "

re='^[0-9]+$'

read  ELECCION

if [ -z "$ELECCION" ]; then
echo "U dont know how to read bruh?"
exit 
fi

if ! [[ "$ELECCION" =~ $re ]] ; then
   echo "U dont know how to read bruh?"
   exit
fi

if [ "$ELECCION" -gt $i ]; then
echo "U dont know how to read bruh?"
exit 
fi


if [ ! -d $LOG_DIR ]; then
    echo "log dir not found, creating $LOG_DIR"
    mkdir -p $LOG_DIR
fi


echo "$(date $HORA)--------ssh $DEBUG -l $LUSER ${MAQUINA[$ELECCION]}" >> $LOG_FILE
ssh $DEBUG -l $LUSER ${MAQUINA[$ELECCION]}
EXITUS=$(echo $?)
echo "$(date $HORA)--------finished ssh $DEBUG -l $LUSER ${MAQUINA[$ELECCION]} ---- $EXITUS" >> $LOG_FILE

;;

esac
exit




