#!/bin/ksh
##Potaje6
##Grep stuff in .ssh/known_hosts, typing the whole hostname is for niggers and fags
##Disable ssh's know_hosts encryption to use this
##Require ksh

i=0
LUSER=sistemas
x=1
z=0
bold=$(tput bold)
normal=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
color=red
HORA=+%Y-%m-%d--%H:%M:%S
EXEC_DIR=$(dirname $0)
EXEC_NAME=$(basename $0)
LOG_DIR=$EXEC_DIR/logs
LOG_FILE=$LOG_DIR/connections
LIST_FILE=$EXEC_DIR/list
MODE=normie
NOLOG=0
SCP=0
SEND=0
GET=0

normie(){
if (( $i % 2 )); then
    color=$red
else
    color=$yellow
fi
}

faggot(){
z=$(($z+1))
if [ $z -eq 6 ]; then z=1; fi
color=$(tput setaf ${z})
}

##Captura de salida
trap force_exit SIGINT


force_exit(){
        echo 
        echo "Exiting..."
        exit 3
}

logdis(){
    if [ $NOLOG -eq 0 ]; then
        if test -f $LOG_FILE; then
        echo "$(date $HORA)--------$@" >> $LOG_FILE
            else echo "Log file $LOG_FILE missing, not logging"
        fi
    fi
}

print_uso(){
cat <<EOF
        Usage:
        ./script [-h|-v|-u|-r] string_to_grep
        This shit logs all ur activity for the NSA in $LOG_FILE
        -v verbose mode
        -u user
        -r root
        --nolog do not log access
        --send/--get -f [file] [string_to_grep] (works with the rest of parms)
            -R recursive
        --faggot = do it faggot
EOF
exit
}

#send stuff
send_files(){
    scp $DEBUG $RECUSIVE $1 $3@$2:
    EXITUS=$(echo $?)
    logdis finished scp $DEBUG $RECUSIVE $1 $3@$2: ---- $EXITUS
    exit $EXITUS

}

#get stuff
get_files(){
    scp $DEBUG $RECUSIVE $3@$2:$1 .
    EXITUS=$(echo $?)
    logdis finished scp $DEBUG $RECUSIVE $3@$2:$1 . ---- $EXITUS
    exit $EXITUS

}

#check if we have to send or get
send_or_get(){
if [ -z $SCP_FILE ]; then
    echo "File to send/get not specified"
    print_uso
fi

if [[ $SEND -eq 1 && $GET -eq 1 ]]; then
    echo "Use send or get, not both"
fi
if [ $SEND -eq 1 ];then
    send_files $SCP_FILE $2 $3
fi

if [ $GET -eq 1 ];then
    get_files $SCP_FILE $2 $3
fi
}

if [ $# -eq 0 ];then
print_uso
fi

while [ $# -gt 0 ];
do
    case $1 in
-h)     
print_uso
;;
-u) LUSER=$2
shift
shift
;;
-r) LUSER=root
shift
;;
--faggot) MODE=faggot
shift
;;
-v) DEBUG=-v
shift
;;
--nolog) NOLOG=1
shift
;;
--send) SEND=1
         SCP=1
shift
;;
--get) GET=1
       SCP=1
shift
;;
-f) SCP_FILE=$2
shift
shift
;;
-R) RECUSIVE=-r
shift
;;
*) break
;;
esac
done

if [ $# -eq 0 ];then
print_uso
fi

#solo 1 de los 2 modos puede estar activo, o fichero list o known_hosts
cat $HOME/.ssh/known_hosts | cut -d "," -f1 | cut -d " " -f1 | uniq -u |sort | grep -- $1 |\

#if [ ! -f $LIST_FILE ]; then
#    touch $LIST_FILE
#fi

#grep -v ^# $LIST_FILE |\
#uniq -u |sort | grep -- $1 |\
while read MAQUINA ; do
i=$(($i+1))

$MODE

MAQUINA[$i]=$MAQUINA
#eval echo "${color}$i${normal} = ${color}$MAQUINA${normal}"
echo "${color}$i${normal} = ${color}$MAQUINA${normal}"
done

case $i in
0) echo "Not found in list"
        nc $DEBUG -w 3 -z $1 22 > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "${bold}$1${normal} exist and got 22 open"
            if [ $SCP -eq 1 ]; then
            send_or_get $SCP_FILE $2 $LUSER
            fi
            ssh $DEBUG -o ServerAliveInterval=120 -l $LUSER $1
            logdis finished ssh $DEBUG  -l $LUSER $1 ---- $EXITUS
        fi
        exit 
;;      
1) echo "${bold}${MAQUINA[$i]}${normal} ${bold}FOUND${normal}"
            if [ $SCP -eq 1 ]; then
            send_or_get $SCP_FILE ${MAQUINA[$i]} $LUSER
            fi
        ssh $DEBUG -o ServerAliveInterval=120 -l $LUSER ${MAQUINA[$i]}
        logdis finished ssh $DEBUG  -l $LUSER ${MAQUINA[$i]} ---- $EXITUS
;;      
*)

printf "Type 1 to ${bold}$i${normal} to login: "

re='^[0-9]+$'

read  ELECCION

if [ -z "$ELECCION" ]; then
echo "U dont know how to read bruh?"
exit 
fi

if ! [[ "$ELECCION" =~ $re ]] ; then
   echo "U dont know how to read bruh?"
   exit
fi

if [ "$ELECCION" -gt $i ]; then
echo "U dont know how to read bruh?"
exit 
fi


#if [ ! -d $LOG_DIR ]; then
#    echo "log dir not found, creating $LOG_DIR"
#    mkdir -p $LOG_DIR
#fi

    if [ $SCP -eq 1 ]; then
            send_or_get $SCP_FILE ${MAQUINA[$ELECCION]} $LUSER
    fi

logdis ssh $DEBUG -l $LUSER ${MAQUINA[$ELECCION]}
ssh $DEBUG -o ServerAliveInterval=120 -l $LUSER ${MAQUINA[$ELECCION]}
EXITUS=$(echo $?)
logdis finished ssh $DEBUG  -l $LUSER ${MAQUINA[$ELECCION]} ---- $EXITUS

;;

esac
exit



