#!/bin/bash


case $1 in
	next )
		cmus-remote --server /run/user/1000/cmus-socket -n
		notify-send "$(cmus-remote -Q | grep tag | head -n 3  | sort -r | cut -d ' ' -f 3-  | head -n 1)" "$(cmus-remote -Q | grep tag | head -n 3  | sort -r | cut -d ' ' -f 3-  | tail -n 2)"
	;;
	back )
		cmus-remote --server /run/user/1000/cmus-socket -r
		notify-send "$(cmus-remote -Q | grep tag | head -n 3  | sort -r | cut -d ' ' -f 3-  | head -n 1)" "$(cmus-remote -Q | grep tag | head -n 3  | sort -r | cut -d ' ' -f 3-  | tail -n 2)"
	;;
esac
