#!/bin/bash
case $1 in
        *T* ) eval VAR="$(echo "scale=2; $(echo $1| rev | cut -c 2- | rev)*1073741824" | bc)"
                ;;
        *G* ) eval VAR="$(echo "scale=2; $(echo $1| rev | cut -c 2- | rev)*1048576" | bc)"
                ;;
        *M* ) eval VAR="$(echo "scale=2; $(echo $1| rev | cut -c 2- | rev)*1024" | bc)"
                ;;
        *K* ) VAR=$(echo $1| rev | cut -c 2- | rev)
                ;;
esac
echo $VAR
