#!/bin/ksh
##Script para que salga el grito NOOOOOOOO de enjuto mojamuto cuando no llegue a X

##Declare vars
LOCKFILE=$HOME/.ENJUTO
NOOOO=/home/dmolinao/scripts/parametros/Enjuto_Mojamuto-_Nooooooooooooo....wav
IP=192.168.150.150
ICO=/home/dmolinao/scripts/parametros/enjuto.jpeg
LOCKFILE=$HOME/.ENJUTO



if [ -f $LOCKFILE  ]; then
	exit
else
echo $$ > $LOCKFILE
fi


trap force_exit SIGINT SIGTERM

force_exit(){
rm -f $LOCKFILE
exit 0
}


export DISPLAY=:0



while true ; do

if [ ! -f $LOCKFILE ]; then
	exit
fi 
nc -w 4 -z $IP 22

if [ $? -ne 0 ]; then
	paplay $NOOOO &
	/usr/bin/notify-send -i $ICO  "NO FUNSIONA LA VPN"
fi
sleep 30
done
