#!/bin/bash
##Daniel Molina
##Script para controlar volument etc por comando + parametro, util para hotkey


        case $1 in
        "up")
                amixer -D pulse sset Master 10%+ > /dev/null
                notify-send -t 20 $(amixer -D pulse get Master |  grep  Front| grep --color=never   -E '[0-9]'| head -1 | awk '{print$5}' | sed 's/\[//g' | sed 's/\]//g')

;;
        "down")
                amixer -D pulse sset Master 10%- > /dev/null
                notify-send -t 20 $(amixer -D pulse get Master |  grep  Front| grep --color=never   -E '[0-9]'| head -1 | awk '{print$5}' | sed 's/\[//g' | sed 's/\]//g')

;;
        "mute")
                amixer -D pulse sset Master mute > /dev/null
                notify-send -t 20 $(amixer -D pulse get Master |  grep  Front| grep --color=never   -E '[0-9]'| head -1 | awk '{print$5}' | sed 's/\[//g' | sed 's/\]//g')

;;
        "unmute")
                amixer -D pulse sset Master unmute > /dev/null
                notify-send -t 20 $(amixer -D pulse get Master |  grep  Front| grep --color=never   -E '[0-9]'| head -1 | awk '{print$5}' | sed 's/\[//g' | sed 's/\]//g')

;;
                *)
                shift
        esac




