#!/bin/bash
#Potaje6 
#Absurdly minimalistic, self hosted via xinetd replacement for ix.io or sprunge.us
FILEPATH=/apps/notes/stuff/
FILENAME="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 ; echo '')"
DAYS=30

if [ "$1" == "--clean" ]; then
find $FILEPATH -type f ! -name "index.html" -mtime +$DAYS -delete
exit
fi

until [ ! -f ${FILEPATH}${FILENAME} ]; do
	FILENAME="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 ; echo '')"
done

trap force_exit SIGINT


force_exit(){
        echo $FILENAME
        exit 0
}

cat  > ${FILEPATH}${FILENAME}

echo https://notes.ismyshit.online/${FILENAME}
